seed: 32
fe: 1
proj: 1
num_workers: 8
aug_num: 25
epoch: 10
batch: 16
lr: 0.0001
num_gc_layers: 2
head_layers: 1
hidden_dim: 256
residual: 0
JK: "sum"
pool: "mean"
num_latent_factors: 16
tau: 0.2
drop_ratio: 0.3
log_dir: "log"
gam1:  1.0
gam2:  10.0
eps:   2.0
